"""empty message

Revision ID: 600862e5c945
Revises: 
Create Date: 2019-10-16 22:08:14.781803

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '600862e5c945'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_datetime', sa.DateTime(), nullable=True),
    sa.Column('incident_date', sa.Date(), nullable=True),
    sa.Column('incident_time', sa.Time(), nullable=True),
    sa.Column('incident_year', sa.Integer(), nullable=True),
    sa.Column('incident_day_of_the_week', sa.String(length=12), nullable=True),
    sa.Column('report_datetime', sa.DateTime(), nullable=True),
    sa.Column('row_id', sa.BigInteger(), nullable=True),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('incident_number', sa.Integer(), nullable=True),
    sa.Column('cad_number', sa.String(length=12), nullable=True),
    sa.Column('report_type_code', sa.String(length=12), nullable=True),
    sa.Column('report_type_description', sa.Text(), nullable=True),
    sa.Column('filed_online', sa.String(length=12), nullable=True),
    sa.Column('incident_code', sa.String(length=12), nullable=True),
    sa.Column('incident_category', sa.Text(), nullable=True),
    sa.Column('incident_subcategory', sa.Text(), nullable=True),
    sa.Column('incident_description', sa.Text(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('intersection', sa.Text(), nullable=True),
    sa.Column('cnn', sa.String(length=12), nullable=True),
    sa.Column('police_district', sa.String(length=30), nullable=True),
    sa.Column('analysis_neighborhood', sa.String(length=30), nullable=True),
    sa.Column('supervisor_district', sa.String(length=12), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('point', geoalchemy2.types.Geometry(geometry_type='POINT'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_table('incident')
    # ### end Alembic commands ###
