"""empty message

Revision ID: bf5cdcfe088d
Revises: 
Create Date: 2019-09-25 17:36:41.004691

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'bf5cdcfe088d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_datetime', sa.DateTime(), nullable=True),
    sa.Column('incident_date', sa.Date(), nullable=True),
    sa.Column('incident_time', sa.Time(), nullable=True),
    sa.Column('incident_year', sa.Integer(), nullable=True),
    sa.Column('incident_day_of_the_week', sa.String(length=12), nullable=True),
    sa.Column('report_datetime', sa.DateTime(), nullable=True),
    sa.Column('row_id', sa.BigInteger(), nullable=True),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('incident_number', sa.Integer(), nullable=True),
    sa.Column('cad_number', sa.String(length=12), nullable=True),
    sa.Column('report_type_code', sa.String(length=12), nullable=True),
    sa.Column('report_type_description', sa.Text(), nullable=True),
    sa.Column('filed_online', sa.String(length=12), nullable=True),
    sa.Column('incident_code', sa.String(length=12), nullable=True),
    sa.Column('incident_category', sa.Text(), nullable=True),
    sa.Column('incident_subcategory', sa.Text(), nullable=True),
    sa.Column('incident_description', sa.Text(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('intersection', sa.Text(), nullable=True),
    sa.Column('cnn', sa.String(length=12), nullable=True),
    sa.Column('police_district', sa.String(length=30), nullable=True),
    sa.Column('analysis_neighborhood', sa.String(length=30), nullable=True),
    sa.Column('supervisor_district', sa.String(length=12), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('point', geoalchemy2.types.Geometry(geometry_type='POINT'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incident')
    # ### end Alembic commands ###
